<div><?php echo $block->getGridHtml() ?></div>
<script>
	require(['jquery'], function ($){
		$('#DataTable .col-increment_id a').click(function (e){
			e.preventDefault();

			$.ajax({
				cache: false,
				url: '<?php echo $this->getUrl('*/*/getRentalModal', ['renderer' => 'byorder']) ?>',
				data: { id: $(this).data('order_id') },
				dataType: 'json',
				type: 'get',
				beforeSend: function (){
					$(document.body).trigger('processStart');
				},
				complete: function () {
					$(document.body).trigger('processStop');
				},
				success: function (data) {
					$('<div>' + data.html + '</div>').modal({
						title: data.title,
						autoOpen: true
					});
				},
				error: function (jqXHR, textStatus, errorThrown){
					$('<div style="white-space: pre;overflow: auto;">' + jqXHR.responseText + '</div>').modal({
						title: textStatus,
						autoOpen: true
					});
				}
			});
		});
	});
</script>