<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var \Magento\Framework\Pricing\Render\Amount $block */
/** @var \SalesIgniter\Rental\Helper\Data $helperRental */

$helperRental = \Magento\Framework\App\ObjectManager::getInstance()->create( '\SalesIgniter\Rental\Helper\Data' );
?>
<?php if ( ! $helperRental->isRentalType( $block->getSaleableItem()->getId() ) ): ?>
	<?= /* @escapeNotVerified */
	$block->formatCurrency( $block->getDisplayValue(), (bool) $block->getIncludeContainer() ) ?>
<?php endif; ?>
